[package]
name = "plotsirv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"

valence = { path = "../valence" }
valence_protocol = { path = "../valence_protocol" }
